### ISSUE TITLE
User story - Use on both desktop and mobile

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/HalloweenHackathon#1]
### Story

As a **user**, I can **use the website/play the game on both mobile and desktop** so that I can **have multiple ways to enjoy myself**.

### Acceptance Criteria

- On mobile, the user should be able to play the games the same as on desktop
- The functionality should not change on each device

### Tasks

- [ ] Develop a responsive layout for mobile
- [ ] Develop a responsive layout for desktop
- [ ] Ensure that events such as click events work on mobile too
