### ISSUE TITLE
User story - Accessible navigation

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/HalloweenHackathon#2]
### Story

As a **user**, I can **navigate with a keyboard** so that I am **not restricted using a mouse**.

### Acceptance Criteria

- User should be able to use the website without a mouse
- No functionality should be reduced by only using the keyboard
- User should understand _how to_ navigate

### Tasks

- [x] Ensure that all "action" buttons are tabbable on desktop
- [x] Ensure that new windows opened receive focus
- [ ] Provide instructions on how to navigate, or an animation
