### ISSUE TITLE
User story - Audio and sound effects

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/HalloweenHackathon#3]
### Story

As a **user**, I can **hear sounds effects and music as I play** so that I can **become immersed in the game**.

### Acceptance Criteria

- Sounds effects for different actions such as opening doors, footsteps, etc.
- Background sound effects such as wind/rain/thunder
- Eery background music
- Sound effects and music should have the appropriate volume
- Sound effects and music should be mutable

### Tasks

- [x] Source different sound effects that can be used in the game
- [x] Add sound effects to the assets folder
- [x] Call function to play music at appropriate times in game
- [x] Call function to play sound effects at appropriate times
- [x] Add controls to mute audio and conditions to _not_ play audio if it is muted
