### ISSUE TITLE
User story - Integration of all the minigames in the mansion

### ISSUE THREAD

**Issue by patchamama** [stephendawsondev/HalloweenHackathon#39]
### Story

As a **user**, I can **do some action** so that I can **achieve some goal**.
As a **user**, I can **access the mini-games from the mansion** so I can **progress through the challenges presented to me**.

### Acceptance Criteria

- Mini-games should not deploy on their own unless contact is made with the interactive objects.
- Show help facility to display mansion objects (doors) that allow access to mini-games.
- Access to mini-games should be available in desktop and mobile view.

### Tasks

- [ ] Integrate access to mini-games using the mouse or keyboard movement.
- [ ] Show help image to point to interactive objects.
- [ ] Check desktop and mobile view functionality.
