### ISSUE TITLE
User story - Storytelling

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/HalloweenHackathon#4]
### Story

As a **user**, I can **read interesting copy/text** so that I can **I am interested in the story and want to progress**.

### Acceptance Criteria

- The story is fun/spooky/engaging
- The story has multiple paths that the player can take
- The story has a conclusion/multiple endings

### Tasks

- [x] Write out some general ideas for the story
- [x] Map out the possible paths of the user (potentially using a flowchart)
- [x] Write the text/dialogue of the story
