### ISSUE TITLE
User story - Store player's game status

### ISSUE THREAD

**Issue by patchamama** [stephendawsondev/HalloweenHackathon#43]
### Story

As a **user**, I can **do all the exercises I am asked to do (without repeating them)** in order **to achieve the final challenge that is set for me**.

### Acceptance Criteria

- If a game has not been fulfilled, let the game be replayed.
- Once an exercise-game has been completed, it shall not be accessed again.
- Once all the games have been completed, the final prize will be awarded.

### Tasks

- [ ] Accessing the games if they have not been completed
- [ ] Save the status of a completed game and disable access to it.
- [ ] If all games have been completed, switch to the next scenario...
