### ISSUE TITLE
Epic - Minigames

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/HalloweenHackathon#5]
### Epic

As a **user**, I can **play some minigames** so that I can **be entertained and experience some variety when using the app**.

### Acceptance Criteria

- Minigames can be played on both mobile and desktop
- Minigames do can be removed or added to the story without disrupting the flow
- Completing a minigame has a positive impact on the user's score, or a negative impact if they lose (e.g. lives lost)

### Tasks

- [x] Create minigames in self-contained functions that can be called when an action item is clicked
- [x] #6 (Create a hangman minigame)
- [x] #35 (Create a quiz minigame)
- [x] #9 (Create a memory match minigame)

> [!NOTE]
> More minigames can be added if we have capacity
