### ISSUE TITLE
User story - Hangman minigame

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/HalloweenHackathon#6]
For #5 (Minigames Epic)

### Story

As a **user**, I can **play a hangman minigame** so that I can **get some variety from the overall app**.

### Acceptance Criteria

- Hangman game works on both mobile and desktop
- Letters chosen should be tab-able for keyboard users
- Potential words should be related to Halloween or scary things

### Tasks

- [x] Create a wireframe for the game
- [x] Source image(s) for the game
- [ ] Source word list for the game
- [x] Create game code

**Comment by stephendawsondev** [comment]
This is nearly done, but just need to add local storage and the new word list.
